# Generated by Django 4.2.3 on 2023-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_teachermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='image',
            new_name='img',
        ),
    ]
