# Generated by Django 4.2.3 on 2023-07-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_rename_image_teachermodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='image/')),
                ('Join_Date', models.DateField(auto_now_add=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursemodel')),
            ],
        ),
    ]
